FROM java:openjdk-8-jdk

# 3.9.0 ee branch
# docker build -t mitchd/mmc .
# docker run -itd --name mmc -p 8585:8585 mitchd/mmc
#
# docker run --rm -it --net=host mitchd/mmc bash
#

MAINTAINER Mitch Dresdner <mdresdner@terathink.com>

USER root

WORKDIR /opt
RUN useradd --user-group --shell /bin/false mule && chown mule /opt 


COPY    ./mmc-3.8.x-web.tar.gz /opt
COPY    ./start.sh /opt

RUN		tar xzf mmc-3.8.x-web.tar.gz \
		  && ln -s mmc-3.8.x-web mmc \
		  && chmod 755 mmc-3.8.x-web \
		  && chmod 755 start.sh \
		  && rm mmc-3.8.x-web.tar.gz

# Mule environment vars
ENV MMC_HOME /opt/mmc

# Volume mount points
# VOLUME ["/opt/mmc/apache-tomcat-7.0.52/logs", "/opt/mmc/apache-tomcat-7.0.52/conf", "/opt/mmc/apache-tomcat-7.0.52/bin"]

# Mule work directory
# WORKDIR /opt

USER mule

# start tomcat && tail -f /var/lib/tomcat7/logs/catalina.out
CMD [ "./start.sh" ]

# Expose default http ports
EXPOSE 8585

